config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tailwindcss/:anything', to: redirect('/')

  get 'tasks', to: 'tasks#index'
  post 'tasks', to: 'tasks#create', as: 'create_task'
  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy_task'
  patch 'tasks/:id', to: 'tasks#update', as: 'update_task'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      @task.completed = params[:task][:completed] == '1'
      @task.save
      redirect_to task_path(@task)
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_with model: @task, url: update_task_path(@task), method: :patch do |form| %>
  <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :details, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :details, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :completed, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.check_box :completed, class: "form-checkbox h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded" %>
    <%= form.label :completed, class: "ml-2" %>
  </div>

  <div class="flex items-center justify-center">
    <%= form.submit class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

<%= link_to "Back to Task", task_path(@task) %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<table>
  <thead>
    <tr>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= check_box_tag "completed[]", task.id, task.completed %>&nbsp;<%= link_to task.title, task_path(task) %></td>
        <td><%= link_to 'Delete', destroy_task_path(task), method: :delete, data: { confirm: 'Are you sure you want to delete this task?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Add Task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with model: @task, url: create_task_path do |form| %>
  <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :details, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :details, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="flex items-center justify-center">
    <%= form.submit class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

<%= link_to "Back to List", tasks_path %>

app/views/tasks/show.html.erb
<h1>Task Details</h1>

<p><strong>Title:</strong> <%= @task.title %></p>
<p><strong>Details:</strong> <%= @task.details %></p>
<!-- <p><strong>Completed:</strong> <%= check_box_tag "completed", "completed", @task.completed, disabled: true %></p> -->

<% if @task.completed %>
  <p><%= check_box_tag "completed", "completed", true, disabled: true %> This task is completed</p>
<% else %>
  <p><%= check_box_tag "completed", "completed", false, disabled: true %> This task is not completed yet</p>
<% end %>

<%= link_to "Edit Task", edit_task_path(@task), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
<%= link_to "Back to List", tasks_path %>